#! /bin/bash

set -e
eval $(grep 'VERSION *=' setup.py | tr '[:upper:]' '[:lower:]' | sed 's/ *= */=/')
tag="v$version"
git tag "$tag" || printf 'WARNING: tag "%s" already exists\n' "$tag"
git push --tags
printf '😼 Now Github Actions should follow...\n'
